### ISSUE TITLE
manifest for not found error in docker pull or docker run 

### ISSUE THREAD

**Issue by patrickelectric** [mauricek/qtwasm_builder#4]
```
$ docker pull maukalinow/qtwasm_builder
Using default tag: latest
Error response from daemon: manifest for maukalinow/qtwasm_builder:latest not found: manifest unknown: manifest unknown
```

**Comment by mauricek** [comment]
Ah this is correct, as I changed the tags recently to maukalinow/qtwasm_builder:<branch>_latest.
I'll update this soon. in the meantime, feel free to locally change it to your branch of preference. Probably 5.13_latest as tag.

**Comment by mauricek** [comment]
Fixed with 645e3ad523908a22c90ee57dc479a26e25be1fef

**Comment by patrickelectric** [comment]
Hey @mauricek thanks for the updates! This docker is really helpful to test Qt webasm, is there any future plan to create a docker for Qt android or do you know one ?

**Comment by mauricek** [comment]
@patrickelectric thx for the nice words, really appreciated.
Qt/Wasm inside docker was done as an experiment for the blog post to see what could be provided. For now, there are no immediate plans. That doesn't mean that it will not happen, it is a matter of when we have time to put effort into it.
Personally, I can see the value and also the benefits.

Does your comment imply that you are using it in production or for research? The reason is that on other reported bugs, the idea has been to always use a stable release and not the latest available version from git. That would certainly help for production usage, not necessarily to check updates.
